version: '3.8'

services:
    api:
        build: ./backend
        image: cloudprojectcs5412.azurecr.io/cloud-api
        ports: 
            - "5000:5000"

    client:
        build: ./frontend
        image: cloudprojectcs5412.azurecr.io/cloud-client
        ports:
            - "8080:8080"
        volumes:
            - "/app/node_modules"