version: '3.8'

services:
    api:
        build: ./backend
        image: CloudProjectCS5412.azurecr.io/cloud-api
        ports: 
            - "5000:5000"

    client:
        build: ./frontend
        image: CloudProjectCS5412.azurecr.io/cloud-client
        volumes:
            - '/app/node_modules'
        ports:
            - "8080:8080"